### PR TITLE
localisation/add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by 0EAC**

### CODE REVIEW

**Comment by tdjsnelling** [comment]
Thanks for the PR! There is still a lot of work to do on the localisation front, I have only covered a fraction of the app so far. I will leave this pull request open for now, and when I get around to covering more pages the Chinese translations can be added here

**Comment by 0EAC** [comment]
> Thanks for the PR! There is still a lot of work to do on the localisation front, I have only covered a fraction of the app so far. I will leave this pull request open for now, and when I get around to covering more pages the Chinese translations can be added here

Thanks reply, I'll keep this patch for more chinese translation commits in the future.

**Comment by tdjsnelling** [comment]
Hi @0EAC 

The [feature/localisation](https://github.com/tdjsnelling/sqtracker/pull/13) branch has been updated – the locales have now each been moved to their own files and most of the strings in the app are added thanks to @smlinux contributing their Russian translation.

If you wish, you can now continue with your Simplified Chinese translation – any efforts are greatly appreciated!

**Comment by 0EAC** [comment]
> Hi @0EAC
> 
> The [feature/localisation](https://github.com/tdjsnelling/sqtracker/pull/13) branch has been updated – the locales have now each been moved to their own files and most of the strings in the app are added thanks to @smlinux contributing their Russian translation.
> 
> If you wish, you can now continue with your Simplified Chinese translation – any efforts are greatly appreciated!

Sorry, my wrong operation caused the PR to be closed, but I still hope to continue to complete the related translation work.give me a bit more time plz.

**Comment by 0EAC** [comment]
Hi @tdjsnelling,
I made a preliminary Chinese translation based on the text content of en.json. 
As I explore more about the sqtracker project, I will improve the translation.

**Pull request merged**
