### PR TITLE
feature/localisation

### PR DESCRIPTION
**Pull request by tdjsnelling**
Issue https://github.com/tdjsnelling/sqtracker/issues/8.

This PR moves hard coded strings to the English locale in the `locales.json` file.

Pages to cover:

- [x] splash
- [x] log in
- [x] register
- [x] password reset initiate
- [x] password reset finalise
- [x] home
- [x] browse
- [x] search
- [x] upload
- [x] requests
- [x] announcements
- [x] wiki
- [x] rss
- [x] bookmarks
- [x] profile
- [x] account
- [x] reports
- [x] stats
- [x] torrent

### CODE REVIEW

**Comment by Baklap4** [comment]
Instead of moving everything into one big locale file would it be possible to split these files? for example: 
* `locale.json` -> English since this is the main language
* `locale.fr.json` -> French deviated from locale.json
* `locale.<2-letter-iso-code>.json`

Better would probably be to actually use cultures (`<language>-<region>` for example: `en-us` (english spoken within the United States) or `nl-be` (Dutch spoken in belgium)), react probably has something for this in place already?

**Comment by smlinux** [comment]
As an offtopic. Alternatively, consider embedding a widget, for exemple: https://github.com/get-web/google-translate-custom-widget

**Comment by smlinux** [comment]
Hello.
Added most translation variables:
https://github.com/smlinux/sqtracker/tree/no-avx-translate
There is also a demo site there.

**Comment by tdjsnelling** [comment]
Hi @smlinux 

Thanks for your hard work here, I have just opened PR https://github.com/tdjsnelling/sqtracker/pull/54 for your changes which I will review and merge tomorrow probably.

What is the reason for swapping the MongoDB image? I do not know what the non-AVX difference means. I will probably not keep that change in the compose file as it is not an official image, but I can recommend it in the README for other users if there is a valid need for it.

**Comment by smlinux** [comment]
> What is the reason for swapping the MongoDB image? I do not know what the non-AVX difference means. I will probably not keep that change in the compose file as it is not an official image, but I can recommend it in the README for other users if there is a valid need for it.

Hi.
Of course, it's better to use the official MongoDB image.
I removed AVX for my test server (processor without AVX), because official MongoDB images requires an AVX.

**Comment by smlinux** [comment]
Hi.
Added translation of statistics. Now the Russian translation can also be considered about ~100%
992fef64e84c4e77d199ccdd881eccba9ffc065f

**Pull request merged**
